### ISSUE TITLE
500 from backend on referendum propose

### ISSUE THREAD

**Issue by kacperzuk-neti** [liberland/liberland_frontend#18]
After clicking "Propose" in frontend form, this error is thrown by backend:

```
Unhandled error for request POST /referenda: TypeError: Cannot read property 'id' of null
    at verifyCanCreateReferendum (/home/kacper/liberland/api/common/models/referendum.js:67:13)
    at async /home/kacper/liberland/api/common/models/referendum.js:128:4
```

* frontend: `develop`
* backend: `develop`
* substrate: `develop`

**Comment by kacperzuk-neti** [comment]
Payload sent by frontend:
```
{
  "link": "asd",
  "chainIndex": "0",
  "name": "Hardcoded server name",
  "description": "asd",
  "hash": "hash not needed",
  "additionalMetadata": {},
  "proposerAddress": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
}

```

**Comment by kacperzuk-neti** [comment]
Problem was caused by lack of `blockchain_address` for user in my dev db. Fixed with:
```
> sudo -u postgres psql -d ll_gov_development
ll_gov_development=# update "user" set blockchain_address = '5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY' where email = 'wakanda@wakanda.com';
```
